// Fuente oficial usada para poblar el selector:
// Superintendencia Financiera de Colombia, pagina
// "Indicadores Gerenciales - Series Historicas por Entidades - NIIF a partir de enero de 2016",
// seccion "Bancos", modificada el 27/03/2026.
export const COLOMBIA_BANK_OPTIONS = [
  'Bogota',
  'Popular',
  'Corpbanca',
  'Bancolombia',
  'Citibank',
  'Banco GNB Sudameris S.A.',
  'BBVA',
  'Occidente',
  'BCSC',
  'Davivienda',
  'Scotiabank Colpatria S.A.',
  'Banagrario',
  'AV Villas',
  'Bancien',
  'Bancamia S.A.',
  'W S.A.',
  'Bancomeva',
  'Banco Finandina',
  'Banco Falabella S.A.',
  'Banco Pichincha S.A.',
  'Banco Coopcentral',
  'Banco Santander de Negocios Colombia',
  'Banco Mundo Mujer',
  'Mibanco S. A.',
  'Banco Serfinanza',
  'Banco JPMorgan S.A.',
  'Lulobank',
  'Banco BTG Pactual',
  'Banco Union',
  'Banco Contactar',
] as const;
